// Renderer regression: real models and transforms, isolated from player accounts.
const assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/Alcione/Documents/Codex/2026-10-03/da-u/work/node_modules/playwright');
const root=path.resolve(__dirname,'../..');
const html=`<!doctype html><style>body{margin:0;background:#14211f}canvas{width:100vw;height:100vh}</style><canvas id="scene"></canvas><script type="module">
import * as pc from '/modern/vendor/playcanvas.mjs';import {createActors} from '/modern/actors.js';
const app=new pc.Application(document.querySelector('canvas'),{graphicsDeviceOptions:{antialias:true}});app.setCanvasFillMode(pc.FILLMODE_FILL_WINDOW);app.setCanvasResolution(pc.RESOLUTION_AUTO);app.scene.ambientLight=new pc.Color(.7,.7,.7);
const camera=new pc.Entity();camera.addComponent('camera',{projection:pc.PROJECTION_ORTHOGRAPHIC,orthoHeight:3,clearColor:new pc.Color(.08,.15,.13)});camera.setPosition(4.5,9,10);camera.lookAt(4.5,0,1);app.root.addChild(camera);
const sun=new pc.Entity();sun.addComponent('light',{type:'directional',intensity:1.3});sun.setEulerAngles(45,30,0);app.root.addChild(sun);
const directions=['left','right','up','down'],players=Object.fromEntries(directions.map((dir,i)=>[i,{x:1+i*2,y:1,renderX:1+i*2,renderY:1,hp:100,dir,equipped:{}}]));
const bridge={getPlayer:()=>({x:-100,y:-100,equipped:{}}),getCamera:()=>({x:0,y:0}),getViewBounds:()=>({minX:-10,maxX:20,minY:-10,maxY:20}),getRemotePlayers:()=>players,getMonsters:()=>[],getNpcs:()=>[],getItems:()=>({})};
const actors=await createActors(pc,app,bridge);actors.update(.016);app.start();window.qa={pc,app,actors,players};
</script>`;
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');if(url.pathname==='/'){res.setHeader('Content-Type','text/html');res.end(html);return;}if(url.pathname==='/favicon.ico'){res.writeHead(204).end();return;}const file=path.resolve(root,'.'+url.pathname);if(!url.pathname.startsWith('/modern/')||!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.glb')?'model/gltf-binary':'text/javascript');fs.createReadStream(file).pipe(res);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});const page=await browser.newPage({viewport:{width:1200,height:650}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.qa);await page.waitForTimeout(300);
const named=await page.evaluate(()=>Object.entries(qa.players).map(([id,p])=>{const r=qa.actors.entries.get('remote:'+id),f=r.entity.getWorldTransform().transformVector(new qa.pc.Vec3(0,0,1)).normalize();return{dir:p.dir,facing:{x:f.x,z:f.z}};}));const expected={left:[-1,0],right:[1,0],up:[0,-1],down:[0,1]};for(const row of named){const [x,z]=expected[row.dir];assert.ok(row.facing.x*x+row.facing.z*z>.999,'model faces '+row.dir+': '+JSON.stringify(row.facing));}
if(process.env.FACING_CAPTURE)await page.screenshot({path:process.env.FACING_CAPTURE});
const inferred=await page.evaluate(()=>{const p=qa.players[0];delete p.dir;const result=[];for(const [dx,dz] of [[-1,0],[1,0],[0,-1],[0,1],[-1,1],[1,-1]]){p.renderX+=dx*.1;p.renderY+=dz*.1;qa.actors.update(.016);const r=qa.actors.entries.get('remote:0'),f=r.entity.getWorldTransform().transformVector(new qa.pc.Vec3(0,0,1)).normalize();result.push({dx,dz,dot:(f.x*dx+f.z*dz)/Math.hypot(dx,dz)});}p.dir='right';p.renderX-=.1;qa.actors.update(.016);const f=qa.actors.entries.get('remote:0').entity.getWorldTransform().transformVector(new qa.pc.Vec3(0,0,1)).normalize();return{movement:result,targetFacingX:f.x};});for(const row of inferred.movement)assert.ok(row.dot>.999,'inferred movement facing '+JSON.stringify(row));assert.ok(inferred.targetFacingX>.999,'explicit combat facing remains authoritative while moving');assert.deepEqual(errors,[]);console.log(JSON.stringify({result:'PASS',named,inferred,errors},null,2));
}finally{await browser?.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
